USE MASTER
GO
ALTER DATABASE QUANLYTHUVIEN SET MULTI_USER

USE QUANLYTHUVIEN
GO
BACKUP DATABASE QUANLYTHUVIEN TO DISK = 'D:\\backupQLTV.Bak' WITH NOINIT
BACKUP DATABASE QUANLYTHUVIEN TO DISK = 'D:\\backupQLTV_diff.Bak' WITH DIFFERENTIAL

USE MASTER
GO
ALTER DATABASE QUANLYTHUVIEN SET SINGLE_USER
RESTORE DATABASE QUANLYTHUVIEN FROM DISK = 'D:\\backupQLTV.Bak' WITH NORECOVERY
RESTORE DATABASE QUANLYTHUVIEN FROM DISK = 'D:\\backupQLTV_diff.Bak' 